export const certifications = [
    "ISO 22000",
    "HACCP",
    "FSSC 22000",
    "BRCGS Food Safety",
    "IFS Food",
    "SQF",
    "Global GAP",
    "GMP",
    "FDA Registration",
    "USDA Organic",
    "EU Organic",
    "Halal",
    "Kosher",
    "Fair Trade",
    "Rainforest Alliance",
    "MSC",
    "ASC",
    "Non GMO",
    "Sedex",
    "SMETA",
    "ISO 9001",
    "ISO 14001",
    "ISO 45001",
  ].map((item) => ({
    value: item,
    label: item,
  }));