export const productCategories = [
    "Rice",
    "Wheat",
    "Corn",
    "Barley",
    "Oats",
    "Millets",
    "Spices",
    "Herbs",
    "Seasonings",
    "Fresh Fruits",
    "Fresh Vegetables",
    "Frozen Foods",
    "Dairy Products",
    "Meat",
    "Poultry",
    "Seafood",
    "Coffee",
    "Tea",
    "Beverages",
    "Confectionery",
    "Snacks",
    "Organic Foods",
    "Edible Oils",
    "Sugar",
    "Nuts & Dry Fruits",
    "Pulses & Legumes",
    "Sauces & Condiments",
    "Chocolate Products",
    "Plant Based Foods",
    "Health Supplements",
  ].map((item) => ({
    value: item,
    label: item,
  }));